name: test1
env:
  REPO: saidbenhmed/dendro-backend-prod
  
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with: 
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "v${major}.${minor}.${patch}"
          bump_each_commit: true
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: 'saidbenhmed'
          password: '&2*$Xd/i-pJx@+%'
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-php
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}
      
